### ISSUE TITLE
Стандартизировать используемые символы

### ISSUE THREAD

**Issue by vyshkant** [medieval-rus/epigraphy-workflow#2]
# Проблема

Сейчас нет однозначности в том, какие символы нужно использовать для передачи древнерусских букв.

# Предложение

Составить список таких символов, который был бы общим для всей базы. Это касается также передачи титл и, возможно, выносных букв.

# Приглашение к обсуждению
_здесь будет список людей, приглашенных к обсуждению_

**Comment by savvushka** [comment]
Но идея ставить над второй буквой тоже принадлежит А. А. :-) Пусть он и разрешит спор!

**Comment by Fitisa** [comment]
**ИТАК** мы решили, что
1. выносные буквы мы отмечаем бэкслешем справа **над каждой** из выносных букв
2. после титла, которого совсем не видно мы ставим звездочку * (вместо круглых скобок)
3. после титла, которое видно не целиком мы ставим решетку # [вместо квадратных скобок]
4. титло (независимо от того, где оно стоит в действительности) мы ставим по следующему правилу: над первой буквой, которая стоит **не на своем месте**
4.1 если это число из более чем одного знака, то титло **всегда ставится над вторым знаком**,
4.2 если только в этом числе в источнике титла не стоят над каждым из знаков
